### PR TITLE
Adjusting tag regex to allow numbers in tags (ie: h1,h2...)

### PR DESCRIPTION
**Pull request by ghost**
This makes it work with <h(1|2|3|4|5|6)> and other tags that may have numbers

### CODE REVIEW

**Comment by 2yuri** [comment]
+1

**Comment by max0d41** [comment]
+1

**Comment by MiracleBlue** [comment]
So considering there has been no activity on this repo at all since it was published, and these bugs were really getting to me, I went ahead and made a fork and included your fix and a few of my own, updated the readme and published under a new name.  Please check it out and feel free to submit further contributions, I promise to review them regularly :)

https://github.com/MiracleBlue/autoclose-tags
https://atom.io/packages/autoclose-tags

**Comment by grgrssll** [comment]
Good to know. I remember seeing other problems with it and uninstalled it.
I'll check yours out.

**Pull request merged**
